apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-demo
  namespace: helm-demo
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/demo/hello-world
      version: ">=0.1.0 <1.0.0"
      sourceRef:
        kind: GitRepository
        name: playground
        namespace: flux-system
      interval: 1h
