apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-phlare
  namespace: grafana-phlare
spec:
  interval: 5m
  chart:
    spec:
      chart: phlare
      version: ">=0.1.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    phlare:
      components:
        querier:
          kind: Deployment
          replicaCount: 2
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
              cpu: 100m
        distributor:
          kind: Deployment
          replicaCount: 2
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
              cpu: 500m
        agent:
          kind: Deployment
          replicaCount: 1
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
              cpu: 50m
        ingester:
          kind: StatefulSet
          replicaCount: 3

    minio:
      enabled: false
