apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-helm-demo
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: config-infrastructure
  - name: config-core
  sourceRef:
    kind: GitRepository
    name: playground
  path: ./k8s/apps/demo/helm-demo
  prune: true
