apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-minio-tenant-1
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: config-infrastructure
  - name: app-minio
  - name: config-core
  sourceRef:
    kind: GitRepository
    name: playground
  path: ./k8s/apps/demo/minio-tenant-1
  prune: true
