apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: synapse
  POSTGRES_USER: synapse
  POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF-8"
