apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: searx
resources:
- namespace.yaml
- ingress.yaml
- deployment.yaml
- service.yaml

transformers:
- common-labels.yaml

secretGenerator:
- name: vpn

configMapGenerator:
- name: env-vars
  literals:
  - BASE_URL=https://search.siebjee.nl
- name: settings
