apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: playground
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com/Siebjee/kubernetes.git
  ref:
    branch: master
  secretRef:
    name: ci-key-rsa
