apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator
      version: ">=4.3.7 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 1m
  values:
    operator:
      clusterDomain: minio.k8s-local.io
    console:
      replicaCount: 1
