apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: demo-app-builds

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-app-builds-argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: demo-app-builds
