apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: quotes-bot
namespace: quotes-bot
resources:
- namespace.yaml
- cron-workflow.yaml
- eventsource.yaml
- quotes.yaml
- service-accounts.yaml
- eventbus.yaml
- sensor-slack.yaml
