apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quotes-bot-argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: quotes-bot

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quotes-bot-argo-events-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-argo-events-role
subjects:
- kind: ServiceAccount
  name: argo-events
  namespace: quotes-bot
