apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-argo
namespace: argo
resources:
- namespace.yaml
- custom-argo-cluster-role.yaml
- ui-role.yaml
- install.yaml
- cm.yaml
- ingress.yaml
