apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent-traces
  name: grafana-agent-traces
spec:
  ports:
  - name: grafana-agent-traces-http-metrics
    port: 3100
    targetPort: 3100
  - name: grafana-agent-traces-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    name: grafana-agent-traces
