apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-argo-events
namespace: demo-app-builds
resources:
- namespace.yaml
- eventbus.yaml
- service-accounts/sa-argo-events.yaml
- service-accounts/sa-argo.yaml
- sensors/demo-container-banana.yaml
- sensors/slack-trigger.yaml
- sensors/demo-container-apple.yaml
- sensors/demo-container.yaml
- secrets/secret-slack.yaml
- secrets/secret-minio.yaml
- eventsources/demo-build.yaml
- eventsources/slackhook.yaml
