apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo
namespace: argo
resources:
- ../../base/argo
- secret-argo-sso.yaml
- sa-rbac.yaml
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- configmap-workflow-controller.yaml
