apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-tempo
resources:
- namespace.yaml
- release.yaml
- agent/clusterrrole.yaml
- agent/clusterrrolebinding.yaml
- agent/deployment.yaml
- agent/service.yaml
- agent/serviceaccount.yaml
- agent/servicemonitor.yaml

configMapGenerator:
- name: grafana-agent-traces

patches:
- path: agent/configmap.yaml
