apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-demo
namespace: demo
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- root-deployment.yaml
- apple-deployment.yaml
- banana-deployment.yaml
- service.yaml
- ingress.yaml
