apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgB9o1iz5dv3aGzJ2c4y+2jVkG88ajSKjBK5xbd06RR4DEpsx5OPosV1l9cUl6EBghkZ+qrN8LSm1AEk1+Y+TKLpNgN0MSsSbXoa2Jtzm84sVP3VM/jEjeucJ59uQBBglYoF9FO8o3iQY8JP4r+dgg3BAioqAl03eW88S0FZyKMQMNDpW42Bu5e7j+1D9t8PdvGfNBUq6HUNljrUf//j8gSnk0Yx3Gcl2ndkdl0GBLh0KbF8f1Q1m4pjYHj/3ggfYkH6/zdQM/EGhn+xQLnXUfVUD/gV9L5OL45yOz+/YEZ4lShruJlFfCmHjZvisJAiexH5UKueiF1ZUDv9OD3RhEXitqpnBc8S+Ey5hOlz7sUZtBLXOUYZT8FiLQYfE/DF8RKQ6OuTjcaUlq6hZCnFoz9cVrryzfMQPw8gDhBthTlQ1voTRio2VJSNJD1Mr9MxxlrfDRjyzAfB/R08qG183IW3tpbd2dOzgQz7BnMioAMs9ELy2aQRJFa/ST6vRzTABNiARkhoDa/krGCGPGiiou6U9SPcr8bp5etQkg0WGEd6MMweu/tPvVhecKOfPo8S1J67+XJtY74wuzeu8k8RQIX8De/XoSEQoZE2kHlTP5JC/yqeQk07h8gSSNiVsC0755KoQ1ROrdlPuvRFy9h1DyEE05C3W819zU8XZrgrkgsRSK6KMYxUtOp457MFw7Sxfm7uTCxrre5WOPKm0lD7xhQNHbCwZeZv6DWjRbsAlmDu0wUUL15nrQvQZl6ugpVFLpdhECnMqUDfAq/dnaE+eLIKngpmnVFlOkdcrl8EitNKbGMesoEjqc36Yv8fHb3SkRsryQhwEwkohj5azCPXDUlsWw2J24ROX/vnXI0MEnD8NOMHNE+5iA==
  template:
    metadata:
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
