apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ci-demo-app-builds
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: config-infrastructure
  - name: config-core
  sourceRef:
    kind: GitRepository
    name: playground
  path: ./k8s/ci/demo/demo-app-builds
  prune: true
