apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex-idp
  namespace: dex-idp
spec:
  interval: 1h
  chart:
    spec:
      chart: dex
      version: ">=0.6.3"
      sourceRef:
        kind: HelmRepository
        name: dex-idp
        namespace: flux-system
      interval: 1h
  values:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: dex.siebjee.nl
        paths:
        - path: /
