apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-cf
spec:
  secretStoreRef:
    name: google-cloud
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
  - secretKey: ZONE_ID
    remoteRef:
      key: secret-cf
      version: latest
      property: zone
  - secretKey: TOKEN
    remoteRef:
      key: secret-cf
      version: latest
      property: token
