apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cache-buster
resources:
- namespace.yaml
- job.yaml
- external-secret.yaml
- rbac.yaml

configMapGenerator:
- name: env-vars
  literals:
  - APP_IMAGE=dummy
