apiVersion: v1
kind: ServiceAccount
metadata:
  name: savage
  namespace: cache-buster

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: savage
  namespace: cache-buster
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adam-savage
  namespace: cache-buster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: savage
subjects:
- kind: ServiceAccount
  name: savage
  namespace: cache-buster
