apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: grafana-agent-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-agent-operator
      version: ">=0.2.13 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
