apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  app.kubernetes.io/name: housekeeper
  app.kubernetes.io/component: pods-cleaner
  app.kubernetes.io/managed-by: flux
fieldSpecs:
- path: metadata/labels
  create: true
