apiVersion: v1
kind: ServiceAccount
metadata:
  name: housekeeper
  namespace: housekeeper

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: housekeeper
  namespace: housekeeper
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: housekeeper
  namespace: housekeeper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: housekeeper
subjects:
- kind: ServiceAccount
  name: housekeeper
  namespace: housekeeper
