apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: google-cloud
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: my-awesome-project
      auth:
        workloadIdentity:
          clusterLocation: europe-west4
          clusterName: nothing
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
