apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-demo
  namespace: helm-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/demo/hello-world
      version: ">=0.1.0 <1.0.0"
      sourceRef:
        kind: GitRepository
        name: playground
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: demo.helm.k8s-local.io
        paths:
        - "/"
    autoscaling:
      enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
