apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: config-ci
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: playground
  path: ./k8s/clusters/demo/ci
  prune: true
  validation: client
