apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  values:
    grafana.ini:
      server:
        root_url: https://grafana.example.com
    ingress:
      tls:
      - hosts:
        - grafana.example.com
        secretName: grafana.example.com
      hosts:
      - grafana.example.com
