apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBNfzb3yPEyrWfuD1M/0Mlg8w6r8pbXsi9qRGDPUfgKdi9EPiDZXdmUfuDsn2NGEx8RHNzKMH5IHDyiVIqmKcDv19EwNP9iEXilXAA1nvHP3ROG9pJ7AhlZPjq1e8PzCqUjFugxbLgj1nBiM+7h0CkWOJNZAlsrwNclph95aCR7EiJ8DW5iyKcDLRzzw9bJGlSaJBLSGIfS5Lgjnsfiiv4uNPBt//bIVkTVEUZUTVWhKPzV56GWd4cXkN8wGErmcPNsIlQIVBSMkO8/8TPnwP/BhJ8nxNhC+cB9t8owb3ffLhFPq6ytT91L/rCrn6m0IDUUMZNtHDNAZa2zon5fNq6XnCSA403Ee7ovsijAzwHdJj+pyUhBaH6nNaLqYchm/pyTTC43zmqtle4b9kCO2VvP3Jp2TxND8bXVdQ+ChxSElixjlv0SjURCQRUF2wrdGUxmAOT4adctYGWC+ZxNsrcCkzO7C+f+1l+WLzNjtHidq05GtgwchtSt703HEWrAAYBd/2cPkua5pLV8i3ASDnrtXWXIQssbfxrkJCr4ZEHlkdkvAGLHquHtd2/spsogvj7O/bP8eXqRcf2x3f9PpQC+1L51HarilEd4OK4u8jJHxOhWsCqgYvDu3JVQmmcPqW0Z2HaVOxYX0t8BMJg/lprjdn26QadZDs8WDVaYaubVKDcwZCIKwFf7DbdxVs5EL8i/bKmGWUh+LI/FybMFX92hMu9NymTzR0t81Egknu315afUaGKkKLpByu5PuPlLZE4Bny3HlO94i04/NLpaOQgRQi422igE+kIhx/TWefO1ucUiMxaeZqn5Bzck8md+2S/l2dqkb7C1SFT36lKFEaSAUYNQQVPciiWCjHwUHZKB1fbDZfFImw==
  template:
    metadata:
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
