apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dex-idp
  namespace: dex-idp
data:
  config.yaml: eyJjb25maWciOnsiaXNzdWVyIjoiaHR0cHM6Ly9kZXguazhzLWxvY2FsLm5sIiwic3RvcmFnZSI6eyJ0eXBlIjoibWVtb3J5In0sImNvbm5lY3RvcnMiOlt7InR5cGUiOiJsZGFwIiwiaWQiOiJsZGFwIiwibmFtZSI6IkxEQVAiLCJjb25maWciOnsiaG9zdCI6ImxkYXAubGRhcC5zdmMuY2x1c3Rlci5sb2NhbDozODkiLCJpbnNlY3VyZU5vU1NMIjp0cnVlLCJiaW5kRE4iOiJ1aWQ9c2VydmljZWFjY291bnQsY249dXNlcnMsZGM9ZXhhbXBsZSxkYz1jb20iLCJiaW5kUFciOiJwYXNzd29yZCIsInVzZXJuYW1lUHJvbXB0IjoiU1NPIFVzZXJuYW1lIiwidXNlclNlYXJjaCI6eyJiYXNlRE4iOiJjbj11c2VycyxkYz1leGFtcGxlLGRjPWNvbSIsImZpbHRlciI6IihvYmplY3RDbGFzcz1wZXJzb24pIiwidXNlcm5hbWUiOiJ1aWQiLCJpZEF0dHIiOiJ1aWQiLCJlbWFpbEF0dHIiOiJtYWlsIiwibmFtZUF0dHIiOiJuYW1lIn0sImdyb3VwU2VhcmNoIjp7ImJhc2VETiI6ImNuPWdyb3VwcyxkYz1leGFtcGxlLGRjPWNvbSIsImZpbHRlciI6IihvYmplY3RDbGFzcz1ncm91cCkiLCJ1c2VyTWF0Y2hlcnMiOlt7InVzZXJBdHRyIjoidWlkIiwiZ3JvdXBBdHRyIjoibWVtYmVyIn1dLCJuYW1lQXR0ciI6Im5hbWUifX19XX19
