apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core-dex-idp
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: config-infrastructure
  - name: core-ingress-nginx
  - name: core-ldap
  sourceRef:
    kind: GitRepository
    name: playground
  path: ./k8s/core/local/dex-idp
  prune: true
