apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core-ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: config-infrastructure
  sourceRef:
    kind: GitRepository
    name: playground
  path: ./k8s/core/local/ingress-nginx
  prune: true
