apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
spec:
  image: docker.io/grafana/agent:v0.32.1 # {"$imagepolicy": "flux-system:grafana-agent"}
  metrics:
    externalLabels:
      cluster: development
