apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  app.kubernetes.io/name: grafana-agent
  app.kubernetes.io/component: agent
  app.kubernetes.io/instance: grafana
  app.kubernetes.io/managed-by: flux
fieldSpecs:
- path: metadata/labels
  create: true
