apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace
resources:
- agent.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- logs-instance.yaml
- metrics-instance.yaml
- namespace.yaml
- serviceaccount.yaml

# Default ServiceMonitors
- service-monitors/kubelet.yaml
- service-monitors/cadvisor.yaml

- podlogs.yaml

transformers:
- common-labels.yaml
