apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-argo
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: config-infrastructure
  - name: config-core
  - name: core-ingress-nginx
  sourceRef:
    kind: GitRepository
    name: playground
  path: ./k8s/apps/local/argo
  prune: true
